function q = Dy(a,b,c)
  
  D = ( (a.^2-b.^2)./(2*a.*b) )*log( (sqrt(c.^2 + a.^2 + b.^2 ) - c )./( sqrt(c.^2 + a.^2 + b.^2 ) + c ) ) +...
      ( (c.^2-b.^2)./(2*c.*b) )*log( (sqrt(c.^2 + a.^2 + b.^2 ) - a )./( sqrt(c.^2 + a.^2 + b.^2 ) + a ) )  +...
       (a./(2*b)).*log( (sqrt(c.^2 + a.^2) + c )./(sqrt(c.^2 + a.^2) - c) ) +...
        (c./(2*b)).*log( (sqrt(c.^2 + a.^2) + a)./(sqrt(c.^2 + a.^2) - a) ) +...
        (b./(2*c)).*log( (sqrt(a.^2 + b.^2) - a)./(sqrt(a.^2 + b.^2) + a) ) +...
        (b./(2*a)).*log( (sqrt(c.^2 + b.^2) - c)./(sqrt(c.^2 + b.^2) + c) ) +...
        2*atan( c.*a ./ (b.*sqrt(c.^2 + a.^2 + b.^2)) )  + (c.^3 + a.^3 - 2*b.^3)./(3*c.*a.*b) +...
        %agora os tres ultimos termos faltantes que o Vagson encontrou em 02-05-2022:
        ( (c.^2 + a.^2 - 2*b.^2 )./(3*c.*a.*b) ).*sqrt(c.^2 + a.^2 + b.^2) +...
        (b./(c.*a)).*(sqrt(c.^2 + b.^2) + sqrt(a.^2 + b.^2)) -...
        ( (c.^2 + a.^2)^1.5 + (a.^2 + b.^2)^1.5 + (b.^2 + c.^2)^1.5 )/(3*c.*a.*b) ;


  q = D/pi;

  end