function q = Dz(a,b,c)
%% conforme referencia [30] dissertação Guilherme
   
  D = ( (b.^2-c.^2)./(2*b.*c) )*log( (sqrt(a.^2 + b.^2 + c.^2 ) - a )./( sqrt(a.^2 + b.^2 + c.^2 ) + a ) ) +...
      ( (a.^2-c.^2)./(2*a.*c) )*log( (sqrt(a.^2 + b.^2 + c.^2 ) - b )./( sqrt(a.^2 + b.^2 + c.^2 ) + b ) )  +... 
       (b./(2*c)).*log( (sqrt(a.^2 + b.^2) + a )./(sqrt(a.^2 + b.^2) - a) ) +...
        (a./(2*c)).*log( (sqrt(a.^2 + b.^2) + b)./(sqrt(a.^2 + b.^2) - b) ) +...
        (c./(2*a)).*log( (sqrt(b.^2 + c.^2) - b)./(sqrt(b.^2 + c.^2) + b) ) +...
        (c./(2*b)).*log( (sqrt(a.^2 + c.^2) - a)./(sqrt(a.^2 + c.^2) + a) ) +...
        2*atan( a.*b ./ (c.*sqrt(a.^2 + b.^2 + c.^2)) )  + (a.^3 + b.^3 - 2*c.^3)./(3*a.*b.*c) +...
        %agora os tres ultimos termos faltantes que o Vagson encontrou em 02-05-2022:
        ( (a.^2 + b.^2 - 2*c.^2 )./(3*a.*b.*c) ).*sqrt(a.^2 + b.^2 + c.^2) +...
        (c./(a.*b)).*(sqrt(a.^2 + c.^2) + sqrt(b.^2 + c.^2)) -...
        ( (a.^2 + b.^2)^1.5 + (b.^2 + c.^2)^1.5 + (c.^2 + a.^2)^1.5 )/(3*a.*b.*c) ;
  
  q = D/pi;
  
  end